version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fintech
      MYSQL_DATABASE: fintech
      MYSQL_USER: fintech
      MYSQL_PASSWORD: fintech
    ports:
      - "3306:3306"
    networks:
      - fintech

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fintech

  api:
    image: api:1.0.1
    container_name: api
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
    networks:
      - fintech

  nginx:
    image: nginx:1.0.1
    container_name: nginx
    ports:
      - "8085:8085"
    networks:
      - fintech

networks:
  fintech:
    driver: bridge